# -*- mode: ruby -*-
# vi: set ft=ruby :

#######################################################################
#
#  VAGRANT CONFIG FILE
#
#  Sets up a basic vagrant box VM.
#  Copyright 2013 JT Paasch
#

# Vagrant >=v1.2 required.
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure VAGRANTFILE_API_VERSION do |configure|
  # The name of the base box.
  configure.vm.box = 'centos-6.4'

  # The url to fetch the base box from, if it doesn't exist.
  configure.vm.box_url = 'http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20131103.box'

  # Use a private network which makes it possible to access any open ports on the guest via the IP address.
  configure.vm.network :private_network, ip: '10.36.54.30'

  # Change some VirtualBox defaults.
  configure.vm.provider :virtualbox do |virtualbox|

    # Disable accelerated 3D graphics.
    virtualbox.customize ['modifyvm', :id, '--accelerate3d', 'off']

    # Add 512MB of memory to the VM.
    virtualbox.customize ['modifyvm', :id, '--memory', '512']

    # Use the host's DNS resolvers (not the VMs).
    virtualbox.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']

    # And use the host's DNS proxy too.
    virtualbox.customize ['modifyvm', :id, '--notdnsproxy1', 'on']

  end

  # Let Ansible do the provisioning.
  configure.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'ansible/playbook.yml'
  end

  # Share a folder with the VM.
  configure.vm.synced_folder '..', '/srv/http'
end
